/// <reference lib="webworker" />
/// <reference types="vite/client" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { NavigationRoute, registerRoute } from 'workbox-routing'
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies'
import { CacheableResponsePlugin } from 'workbox-cacheable-response'
import { ExpirationPlugin } from 'workbox-expiration'

// This prevents TypeScript errors in service worker context
declare let self: ServiceWorkerGlobalScope

// Define the __WB_MANIFEST type for TypeScript
declare global {
  interface ServiceWorkerGlobalScope {
    __WB_MANIFEST: Array<{
      url: string;
      revision: string | null;
    }>;
  }
}

// Use with precache injection
const manifest = self.__WB_MANIFEST;

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(manifest);

// Cache page navigations (HTML) with a Network First strategy
registerRoute(
  // Check to see if the request is a navigation to a new page
  ({ request }: { request: Request }) => request.mode === 'navigate',
  // Use a Network First caching strategy
  new NetworkFirst({
    // Put all cached files in a cache named 'pages'
    cacheName: 'pages',
    plugins: [
      // Ensure that only requests that result in a 200 status are cached
      new CacheableResponsePlugin({
        statuses: [200],
      }),
    ],
  }),
);

// Cache CSS, JS, and Web Worker requests with a Stale While Revalidate strategy
registerRoute(
  // Check to see if the request's destination is style for stylesheets, script for JavaScript, or worker for web worker
  ({ request }: { request: Request }) =>
    request.destination === 'style' ||
    request.destination === 'script' ||
    request.destination === 'worker',
  // Use a Stale While Revalidate caching strategy
  new StaleWhileRevalidate({
    // Put all cached files in a cache named 'assets'
    cacheName: 'assets',
    plugins: [
      // Ensure that only requests that result in a 200 status are cached
      new CacheableResponsePlugin({
        statuses: [200],
      }),
    ],
  }),
);

// Cache images with a Cache First strategy
registerRoute(
  // Check to see if the request's destination is image
  ({ request }: { request: Request }) => request.destination === 'image',
  // Use a Cache First caching strategy
  new CacheFirst({
    // Put all cached files in a cache named 'images'
    cacheName: 'images',
    plugins: [
      // Ensure that only requests that result in a 200 status are cached
      new CacheableResponsePlugin({
        statuses: [200],
      }),
      // Don't cache more than 50 items, and expire them after 30 days
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 Days
      }),
    ],
  }),
);

// Special handling for WebAssembly files
registerRoute(
  ({ request }: { request: Request }) => request.url.endsWith('.wasm'),
  new CacheFirst({
    cacheName: 'wasm-modules',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      {
        // Ensure correct MIME type for WebAssembly files
        handlerDidRespond: async ({ response }: { response: Response }) => {
          const clonedResponse = response.clone();
          return new Response(clonedResponse.body, {
            headers: {
              ...Object.fromEntries(clonedResponse.headers.entries()),
              'Content-Type': 'application/wasm',
            },
            status: clonedResponse.status,
            statusText: clonedResponse.statusText,
          });
        },
      },
    ],
  }),
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Handle offline fallback
const networkOnly = new NetworkFirst({
  networkTimeoutSeconds: 3,
});

interface RouteHandlerParams {
  request: Request;
  url: URL;
  event: FetchEvent;
  params: any;
}

const navigationHandler = async (params: RouteHandlerParams) => {
  try {
    // Attempt to get the resource from the network
    return await networkOnly.handle(params);
  } catch (error) {
    // If offline, return the offline page
    return caches.match('/offline.html');
  }
};

// Register the navigation route
registerRoute(new NavigationRoute(navigationHandler));
